name: "Publish"

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    env:
      PR_TITLE: "Create Release"
      COMMIT_MSG: "chore: create new release"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build package
        run: npm run build
      - name: Create Release
        uses: changesets/action@v1
        id: changesets
        with:
          publish: npm run publish-package
          commit: ${{ env.COMMIT_MSG }}
          title: ${{ env.PR_TITLE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
